//Основные иконки для action'ов
const I = {
    External: 'fa fa-external-link',
    Broom: 'x-fa fa-broom',
    Receipt: 'x-fa fa-file-invoice',
    UserPlus: 'x-fa fa-user-plus',
    UserMinus: 'x-fa fa-user-minus',
    Sdp: 'x-fa fa-file-signature',
    Poruchenja:'x-fa fa-newspaper',
    Archive: 'x-fa fa-archive',
    Dir: 'x-fa fa-question',
    Keyboard: 'x-fa fa-keyboard',
    ArrowCircleLeft: 'x-fa fa-arrow-circle-left',
    ArrowCircleRight: 'x-fa fa-arrow-circle-right',
    ArrowLeft: 'x-fa fa-arrow-left',
    ArrowRight: 'x-fa fa-arrow-right',
    Ban: 'x-fa fa-ban',
    Bell: 'x-fa fa-bell',
    BellO: 'x-far fa-bell',
    Ban: 'x-fa fa-ban',
    Book: 'x-fa fa-book',
    BookReader: 'x-fa fa-book-reader',
    Building: 'x-fa fa-building',
    Calendar: 'x-fa fa-calendar',
    CalendarCheck: 'x-fa fa-calendar-check',
    CalendarMinus: 'x-far fa-calendar-minus',
    CalendarO:'x-far fa-calendar',
    CalendarPlus: 'x-fa fa-calendar-plus',
    CalendarTimes: 'x-fa fa-calendar-times',
    Check: 'x-fa fa-check',
    CheckCircle: 'x-fa fa-check-circle',
    CheckCircleO: 'x-far fa-check-circle',
    CheckSquare: 'x-fa fa-check-square',
    CheckSquareO: 'x-far fa-check-square',
    Chart: 'x-fa fas fa-chart-pie',
    Clipboard:'x-fa fa-clipboard',
    Clock:'x-far fa-clock',
    Clone:'x-fa fa-clone',
    Close:'x-far fa-times-circle',

    Cog:'x-fa fa-cog',
    Cogs:'x-fa fa-cogs',
    Copy:'x-fa fa-copy',
    Cut:'x-fa fa-cut',
    Download:'x-fa fa-download',
    Edit:'x-fa fa-edit',
    Exchange: 'x-fa fa-exchange-alt',
    Envelope:'x-fa fa-envelope',
    EnveloptSquare:'x-fa fa-envelope-square',
    Eye:'x-fa fa-eye',
    File:'x-fa fa-file',
    FileImage:'x-far fa-file-image',
    FileArchive:'x-far fa-file-archive',
    FileText:'x-fa fa-file-alt',
    FileTextO:'x-far fa-file-alt',
    Files:'x-far fa-clone',
    Filter:'x-fa fa-filter',
    Fire:'x-fa fa-fire',
    Folder:'x-fa fa-folder',
    FolderO:'x-far fa-folder',
    FolderOpen:'x-fa fa-folder-open',
    FolderOpenO:'x-far fa-folder-open',
    Font:'x-fa fa-font',
    Gear:'x-fa fa-cog',
    Gears:'x-fa fa-cogs',

    Group:'x-fa fa-users',
    History:'x-fa fa-history',
    Home:'x-fa fa-home',
    Hourglass: 'x-fa fa-hourglass',
    Image:'x-fa fa-image',
    Indent:'x-fa fa-indent',
    Info:'x-fa fa-info',
    InfoCircle:'x-fa fa-info-circle',
    Key:'x-fa fa-key',
    //Leanpub:'x-fas fa-leanpub',
    ListAlt:'x-fa fa-list-alt',
    Lock:'x-fa fa-lock',
    Minus:'x-fa fa-minus',
    MinusCircle:'x-fa fa-minus-circle',
    MinusSquare:'x-fa fa-minus-square',
    MinusSquareO:'x-far fa-minus-square',
    Navicon:'x-fa fa-bars',
    Neuter:'x-fa fa-neuter',
    NewspaperO:'x-far fa-newspaper',
    // NoEncryption: 'x-fa fa-no-encryption',
    Paperclip:'x-fa fa-paperclip',
    Paste:'x-fa fa-paste',
    Pencil:'x-fa fa-pencil-alt',
    PencilSquare:'x-fa fa-pen-square',
    //PencilSquareO:'x-far fa-pencil-square',
    Plus:'x-fa fa-plus',
    PlusCircle:'x-fa fa-plus-circle',
    PlusSquare:'x-fa fa-plus-square',
    PlusSquareO:'x-far fa-plus-square',
    PowerOff:'x-fa fa-power-off',
    Print:'x-fa fa-print',
    Question:'x-fa fa-question',
    QuestionCircle:'x-fa fa-question-circle',
    Recycle:'x-fa fa-recycle',
    Refresh:'x-fa fa-sync-alt',
    Remove:'x-fa fa-remove',
    Reorder:'x-fa fa-ellipsis-v',
    Repeat:'x-fa fa-redo-alt',
    Reply:'x-fa fa-reply',
    ReplyAll:'x-fa fa-reply-all',
    RotateLeft:'x-fa fa-undo',
    //RotateRight:'x-fa fa-rotate-right',
    Save: 'x-fa fa-save',
    Scissors:'x-fa fa-cut',
    Search:'x-fa fa-search',
    SearchMinus:'x-fa fa-search-minus',
    SearchPlus:'x-fa fa-search-plus',
    Send:'x-fa fa-paper-plane',
    SendO:'x-far fa-paper-plane',
    SignIn:'x-fa fa-sign-in-alt',
    ExternalLink: 'x-fa fa-external-link-alt',
    StopCircle: 'x-fa fa-stop-circle',
    SignOut:'x-fa fa-sign-out-alt',
    Sliders:'x-fa fa-sliders-h',
    Spinner:'x-fa fa-spinner',
    StickyNote: 'x-fa fa-sticky-note',
    StickyNoteO:'x-far fa-sticky-note',
    Table:'x-fa fa-table',
    Tasks:'x-fa fa-tasks',
    Cancel:'x-fa fa-times',
    CancelCircle:'x-fa fa-times-circle',
    CancelCircleO:'x-far fa-times-circle',
    Trash:'x-fa fa-trash',
    TrashO:'x-far fa-trash',
    Undo:'x-fa fa-undo',
    Unlock:'x-fa fa-unlock',
    Upload:'x-fa fa-upload',
    User:'x-fa fa-user',
    UserPlus:'x-fa fa-user-plus',
    UserTimes:'x-fa fa-user-times',
    Users:'x-fa fa-users',
    Wrench:'x-fa fa-wrench',
    LevelUp: 'x-fa fa-level-up-alt',
    LevelDown: 'x-fa fa-level-down-alt',
    VerticalArrows:'x-fa fa-arrows-alt-v'
};